// Comprehensive Question Bank - 450 Questions
// Organized by Category (5) x Difficulty (3) = 15 subsets
// 30 questions per subset = 450 total questions

const questionBank = {
    general: {
        beginner: [
            { question: "Which note is the relative minor of C major?", options: ["E minor", "D minor", "F minor", "A minor"], answer: "A minor" },
            { question: "What does tempo describe in music?", options: ["The key signature", "The lyric language", "The instrument brand", "The speed of the beat"], answer: "The speed of the beat" },
            { question: "In 4/4 time, how many quarter-note beats are in one bar?", options: ["2 beats", "3 beats", "8 beats", "4 beats"], answer: "4 beats" },
            { question: "What is a chord progression?", options: ["A list of drum rudiments", "A vocal warm-up scale", "A microphone setup", "An ordered sequence of chords"], answer: "An ordered sequence of chords" },
            { question: "Which symbol raises a note by a semitone?", options: ["Flat (♭)", "Natural (♮)", "Fermata", "Sharp (♯)"], answer: "Sharp (♯)" },
            { question: "What does dynamics refer to?", options: ["The song release date", "The instrument tuning app", "The genre popularity", "The loudness and softness of music"], answer: "The loudness and softness of music" },
            { question: "Which interval spans 7 semitones?", options: ["Major third", "Perfect fourth", "Minor sixth", "Perfect fifth"], answer: "Perfect fifth" },
            { question: "What is syncopation?", options: ["Playing only in major keys", "Using only slow tempos", "Avoiding rhythm changes", "Emphasizing normally weak beats or offbeats"], answer: "Emphasizing normally weak beats or offbeats" },
            { question: "How many semitones are in an octave?", options: ["8", "10", "12", "16"], answer: "12" },
            { question: "What does crescendo mean?", options: ["Getting softer", "Getting louder", "Slowing down", "Speeding up"], answer: "Getting louder" },
            { question: "Which clef is used for high notes?", options: ["Alto clef", "Bass clef", "Treble clef", "Tenor clef"], answer: "Treble clef" },
            { question: "What is a scale?", options: ["A measuring device", "A series of notes in ascending or descending order", "A type of percussion", "A vocal technique"], answer: "A series of notes in ascending or descending order" },
            { question: "How many notes are in a major scale?", options: ["5", "6", "7", "8"], answer: "7" },
            { question: "What does legato mean?", options: ["Separate and distinct", "Smooth and connected", "Very fast", "Very slow"], answer: "Smooth and connected" },
            { question: "Which note comes after G?", options: ["F", "A", "B", "C"], answer: "A" },
            { question: "What is a rest in music?", options: ["A break between songs", "A period of silence", "A type of note", "A musical instrument"], answer: "A period of silence" },
            { question: "What does staccato mean?", options: ["Smooth", "Short and separated", "Connected", "Sustained"], answer: "Short and separated" },
            { question: "How many beats does a whole note get in 4/4 time?", options: ["1", "2", "3", "4"], answer: "4" },
            { question: "What is the distance between two identical notes called?", options: ["Unison", "Octave", "Perfect fifth", "Fourth"], answer: "Octave" },
            { question: "Which time signature is most common in rock music?", options: ["3/4", "6/8", "4/4", "2/2"], answer: "4/4" },
            { question: "What does 'pp' mean in musical notation?", options: ["Moderately soft", "Very loud", "Very soft", "Moderately loud"], answer: "Very soft" },
            { question: "How many sharps are in the G major scale?", options: ["0", "1", "2", "3"], answer: "1" },
            { question: "What is enharmonic equivalence?", options: ["Similar sounding notes", "Different notes with the same pitch", "Loud notes", "Quiet notes"], answer: "Different notes with the same pitch" },
            { question: "What does 'ritardando' mean?", options: ["Gradually getting faster", "Gradually getting slower", "Staying the same tempo", "Suddenly speeding up"], answer: "Gradually getting slower" },
            { question: "Which interval is a tritone?", options: ["Augmented fourth or diminished fifth", "Perfect fifth", "Major third", "Minor sixth"], answer: "Augmented fourth or diminished fifth" },
            { question: "What is a natural sign?", options: ["A sharp symbol", "A flat symbol", "A symbol that cancels a sharp or flat", "A fermata"], answer: "A symbol that cancels a sharp or flat" },
            { question: "How many beats does a half note get in 4/4 time?", options: ["1", "2", "3", "4"], answer: "2" },
            { question: "What does 'fortissimo' (ff) mean?", options: ["Moderately loud", "Very loud", "Moderately soft", "Very soft"], answer: "Very loud" },
            { question: "Which interval has 3 semitones?", options: ["Minor third", "Major second", "Perfect fourth", "Tritone"], answer: "Minor third" },
            { question: "What is a fermata?", options: ["A fast section", "A hold or pause on a note", "A soft ending", "A loud beginning"], answer: "A hold or pause on a note" }
        ],
        intermediate: [
            { question: "What is the circle of fifths used for?", options: ["Teaching rhythm", "Understanding key relationships", "Practicing scales", "Building chords"], answer: "Understanding key relationships" },
            { question: "How many sharps are in D major?", options: ["1", "2", "3", "4"], answer: "2" },
            { question: "What is a secondary dominant?", options: ["The main chord", "A chord that prepares for a non-tonic chord", "A seventh chord", "A minor chord"], answer: "A chord that prepares for a non-tonic chord" },
            { question: "Which chord quality has 3 and 7 semitones?", options: ["Minor", "Major", "Diminished", "Augmented"], answer: "Minor" },
            { question: "What is voice leading?", options: ["Singing technique", "The smooth movement between chords", "Loudness variations", "Tempo changes"], answer: "The smooth movement between chords" },
            { question: "How many flats are in B♭ major?", options: ["1", "2", "3", "4"], answer: "2" },
            { question: "What does 'poco a poco' mean?", options: ["Very slowly", "Little by little", "Suddenly", "Gradually"], answer: "Little by little" },
            { question: "What is modal interchange?", options: ["Key modulation", "Using chords from parallel keys", "Chord inversion", "Suspended chords"], answer: "Using chords from parallel keys" },
            { question: "What is a diminished seventh chord?", options: ["Major 7th with flat 5", "Minor 7th with flat 5", "All semitones are 3", "A dominant 7th"], answer: "Minor 7th with flat 5" },
            { question: "Which scale has an augmented second between degrees 2 and 3?", options: ["Major scale", "Natural minor", "Harmonic minor", "Whole tone"], answer: "Harmonic minor" },
            { question: "What is counterpoint?", options: ["A musical genre", "Simultaneous independent melodic lines", "A type of chord", "Rhythmic displacement"], answer: "Simultaneous independent melodic lines" },
            { question: "How many sharps in A major?", options: ["2", "3", "4", "5"], answer: "3" },
            { question: "What is a suspended chord?", options: ["An unresolved chord", "A chord with 2nd or 4th replacing 3rd", "A diminished chord", "An augmented chord"], answer: "A chord with 2nd or 4th replacing 3rd" },
            { question: "What is inversion in chords?", options: ["Reversing the melody", "Playing chord tones in different order", "Changing the tempo", "Adding harmonies"], answer: "Playing chord tones in different order" },
            { question: "What does 'arpeggio' mean?", options: ["Play notes slowly", "Play chord notes sequentially", "Staccato playing", "Smooth transitions"], answer: "Play chord notes sequentially" },
            { question: "How many flats are in F major?", options: ["0", "1", "2", "3"], answer: "1" },
            { question: "What is a passing tone?", options: ["A non-chord tone between melody notes", "A main melody note", "A chord tone", "A percussion sound"], answer: "A non-chord tone between melody notes" },
            { question: "What is modulation?", options: ["Changing volume", "Changing key", "Changing tempo", "Changing instruments"], answer: "Changing key" },
            { question: "What interval has 5 semitones?", options: ["Perfect fourth", "Perfect fifth", "Major third", "Diminished fifth"], answer: "Perfect fourth" },
            { question: "What is a cadence?", options: ["A fancy chord", "An ending phrase", "A drum pattern", "A vocal technique"], answer: "An ending phrase" },
            { question: "How many flats in E♭ major?", options: ["2", "3", "4", "5"], answer: "3" },
            { question: "What is a neapolitan sixth?", options: ["Italian music", "Flattened supertonic chord", "A minor chord", "A seventh chord"], answer: "Flattened supertonic chord" },
            { question: "What does 'ad libitum' mean?", options: ["In rhythm", "Strictly timed", "At performer's discretion", "Very fast"], answer: "At performer's discretion" },
            { question: "Which intervals are consonant?", options: ["Minor 2nd and tritone", "Unison, octaves, 3rds, 4ths, 5ths, 6ths", "All dissonant intervals", "Only octaves"], answer: "Unison, octaves, 3rds, 4ths, 5ths, 6ths" },
            { question: "What is a pivot chord?", options: ["A chord in the middle", "A chord used to modulate between keys", "The first chord", "The last chord"], answer: "A chord used to modulate between keys" },
            { question: "How many sharps in E major?", options: ["3", "4", "5", "6"], answer: "4" },
            { question: "What is a perfect cadence?", options: ["IV-I", "V-I", "IV-V", "vi-IV"], answer: "V-I" },
            { question: "What does 'glissando' mean?", options: ["Play softly", "Slide between notes", "Play loudly", "Play staccato"], answer: "Slide between notes" },
            { question: "What is parallel motion?", options: ["Opposite direction", "Same direction at same interval", "Different intervals", "Crossover"], answer: "Same direction at same interval" },
            { question: "How many flats in A♭ major?", options: ["3", "4", "5", "6"], answer: "4" }
        ],
        advanced: [
            { question: "What is the Neapolitan chord in C major?", options: ["D♭ major", "E minor", "G major", "F major"], answer: "D♭ major" },
            { question: "How many flats in C♭ major?", options: ["6", "7", "8", "9"], answer: "7" },
            { question: "What is a deceptive cadence?", options: ["V-I", "V-vi", "IV-I", "ii-V"], answer: "V-vi" },
            { question: "What defines Dorian mode?", options: ["Natural minor with raised 6th", "Major with lowered 3rd and 7th", "Natural minor with raised 7th", "Major with raised 4th"], answer: "Natural minor with raised 7th" },
            { question: "What is voice independence in counterpoint?", options: ["Using one melody", "Each voice has independent line", "Same note in all voices", "Parallel motion only"], answer: "Each voice has independent line" },
            { question: "How many sharps in F♯ major?", options: ["5", "6", "7", "8"], answer: "6" },
            { question: "What is a German augmented sixth chord?", options: ["iv with added 6", "I with augmented intervals", "iv with augmented 6 and natural 5", "A major seventh chord"], answer: "iv with augmented 6 and natural 5" },
            { question: "What is a cantus firmus?", options: ["A fast melody", "A pre-existing melody as foundation", "A chord progression", "A rhythmic pattern"], answer: "A pre-existing melody as foundation" },
            { question: "What interval has 8 semitones?", options: ["Major sixth", "Minor sixth", "Perfect fifth", "Augmented fifth"], answer: "Major sixth" },
            { question: "What is homophonic texture?", options: ["All same notes", "One melody with accompaniment", "Multiple independent lines", "Instrumental only"], answer: "One melody with accompaniment" },
            { question: "How many flats in G♭ major?", options: ["5", "6", "7", "8"], answer: "6" },
            { question: "What is an avoided cadence?", options: ["No ending", "Deceptive ending", "Incomplete cadence", "Plagal motion"], answer: "Deceptive ending" },
            { question: "What defines Lydian mode?", options: ["Major with raised 4th", "Major with raised 6th", "Natural minor with raised 6th", "Natural minor with raised 7th"], answer: "Major with raised 4th" },
            { question: "What is polyphonic texture?", options: ["One melody", "Multiple independent equal lines", "Chordal accompaniment", "No melody"], answer: "Multiple independent equal lines" },
            { question: "What interval spans 11 semitones?", options: ["Major seventh", "Octave", "Perfect eleventh", "Minor second"], answer: "Major seventh" },
            { question: "What is a tritone substitution?", options: ["Replacing a chord with another key", "Using diminished chord", "Replacing V7 with ♭II7", "Using parallel chords"], answer: "Replacing V7 with ♭II7" },
            { question: "How many sharps in B major?", options: ["4", "5", "6", "7"], answer: "5" },
            { question: "What is a hemiola?", options: ["Half a measure", "Two against three rhythm", "Silence", "Double note"], answer: "Two against three rhythm" },
            { question: "What defines Phrygian mode?", options: ["Natural minor with lowered 2nd", "Major with lowered 3rd", "Natural minor with raised 3rd", "Major with lowered 6th"], answer: "Natural minor with lowered 2nd" },
            { question: "What is retrogression?", options: ["Moving forward", "Harmony in reverse", "Speeding up", "Slowing down"], answer: "Harmony in reverse" },
            { question: "How many flats in D♭ major?", options: ["4", "5", "6", "7"], answer: "5" },
            { question: "What is the plagal cadence?", options: ["V-I", "IV-I", "vi-IV", "ii-V"], answer: "IV-I" },
            { question: "What defines Mixolydian mode?", options: ["Major with lowered 7th", "Natural minor with raised 6th", "Major with raised 4th", "Natural minor with raised 7th"], answer: "Major with lowered 7th" },
            { question: "What is a suspension?", options: ["Incomplete chord", "Note held over from previous harmony", "Slow tempo", "Loud volume"], answer: "Note held over from previous harmony" },
            { question: "What interval spans 9 semitones?", options: ["Minor sixth", "Major sixth", "Perfect fifth", "Major seventh"], answer: "Major sixth" },
            { question: "What is augmentation?", options: ["Lengthening note duration", "Raising pitch", "Increasing volume", "Speeding tempo"], answer: "Lengthening note duration" },
            { question: "How many sharps in C♯ major?", options: ["6", "7", "8", "9"], answer: "7" },
            { question: "What is diminution?", options: ["Shortening note duration", "Lowering pitch", "Decreasing volume", "Slowing tempo"], answer: "Shortening note duration" },
            { question: "What defines Locrian mode?", options: ["Natural minor with lowered 2nd and 5th", "Major with all lowered", "Natural minor with raised 6th", "Major with lowered 3rd"], answer: "Natural minor with lowered 2nd and 5th" },
            { question: "What is an augmented sixth?", options: ["Interval with 8 semitones", "Interval with 9 semitones", "Chord with raised 5th", "French sixth chord"], answer: "Interval with 9 semitones" }
        ]
    },
    piano: {
        beginner: [
            { question: "On piano, a triad consists of:", options: ["Two notes only", "Five notes always", "Any random cluster", "Three distinct chord tones"], answer: "Three distinct chord tones" },
            { question: "What is middle C commonly called in scientific pitch notation?", options: ["C3", "C5", "B3", "C4"], answer: "C4" },
            { question: "How many white keys are on a standard 88-key piano?", options: ["48", "52", "56", "60"], answer: "52" },
            { question: "How many black keys are on a standard 88-key piano?", options: ["32", "36", "40", "52"], answer: "36" },
            { question: "What are the three pedals on a piano called?", options: ["Volume, tone, echo", "Sustain, soft, una corda", "Loud, medium, soft", "Left, middle, right"], answer: "Sustain, soft, una corda" },
            { question: "What does the right pedal on a piano do?", options: ["Makes notes quieter", "Sustains notes after release", "Shifts sound", "Nothing"], answer: "Sustains notes after release" },
            { question: "What is the lowest note on a 88-key piano?", options: ["A0", "A1", "C1", "C0"], answer: "A0" },
            { question: "What is the highest note on a 88-key piano?", options: ["C8", "B7", "C7", "A8"], answer: "C8" },
            { question: "How many octaves does a standard piano cover?", options: ["5 octaves", "7 octaves", "8 octaves", "10 octaves"], answer: "7 octaves" },
            { question: "What does the left pedal do on a piano?", options: ["Sustains all notes", "Shifts mechanism left", "Quiets the sound", "Raises pitch"], answer: "Shifts mechanism left" },
            { question: "What is a chord inversion where the third is in the bass?", options: ["Root position", "First inversion", "Second inversion", "Third inversion"], answer: "First inversion" },
            { question: "How many notes are in a C major triad?", options: ["2", "3", "4", "5"], answer: "3" },
            { question: "What notes make up a C major triad?", options: ["C-D-E", "C-E-G", "C-E-A", "C-F-G"], answer: "C-E-G" },
            { question: "What notes make up an A minor triad?", options: ["A-C-E", "A-C♯-E", "A-D-E", "A-B-C"], answer: "A-C-E" },
            { question: "What is a broken chord on piano called?", options: ["Staccato chord", "Arpeggio", "Tremolo", "Trill"], answer: "Arpeggio" },
            { question: "What is a double triad?", options: ["Two triads played together", "Six notes", "Two of the same triad", "All of the above"], answer: "All of the above" },
            { question: "What is a seventh chord?", options: ["A triad with added seventh", "Seven notes", "A chord in seventh position", "Three notes"], answer: "A triad with added seventh" },
            { question: "What is the range of a piano called?", options: ["Octave", "Compass", "Scale", "Spectrum"], answer: "Compass" },
            { question: "What is tremolo on piano?", options: ["Rapid repetition", "Soft playing", "Loud playing", "Slow playing"], answer: "Rapid repetition" },
            { question: "What is a trill on piano?", options: ["Quick alternation of two notes", "Loud passage", "Soft passage", "Descending run"], answer: "Quick alternation of two notes" },
            { question: "What is the sustain pedal also called?", options: ["Loud pedal", "Damper pedal", "Soft pedal", "Effect pedal"], answer: "Damper pedal" },
            { question: "What happens when you press the sustain pedal?", options: ["Notes stop immediately", "Dampers lift, notes sustain", "Sound gets louder", "Sound gets softer"], answer: "Dampers lift, notes sustain" },
            { question: "What does a C major scale sound like on piano?", options: ["C-D-E-F-G-A-B-C", "C-D-E-F-G-A-B♭-C", "C-D♭-E-F-G-A-B-C", "All white keys starting on C"], answer: "All white keys starting on C" },
            { question: "What interval is C to G on a piano?", options: ["Third", "Fourth", "Fifth", "Sixth"], answer: "Fifth" },
            { question: "How many fingers should be used for piano playing?", options: ["Both hands, all fingers", "Right hand only", "Left hand only", "4 fingers total"], answer: "Both hands, all fingers" },
            { question: "What is the correct hand position on a piano?", options: ["Flat fingers", "Curved fingers and relaxed wrist", "Straight wrist", "Raised fingers"], answer: "Curved fingers and relaxed wrist" },
            { question: "What is a glissando on piano?", options: ["Staccato notes", "Sliding across keys", "Tremolo effect", "Rapid arpeggios"], answer: "Sliding across keys" },
            { question: "What does 'una corda' mean?", options: ["All strings", "One string", "No strings", "Many strings"], answer: "One string" },
            { question: "What is a chord built on every other note starting from C?", options: ["Diminished", "Augmented", "Major", "All can be correct"], answer: "All can be correct" },
            { question: "What are white keys on a piano?", options: ["Sharps and flats", "Natural notes", "All notes", "Only vowel notes"], answer: "Natural notes" }
        ],
        intermediate: [
            { question: "What is the difference between a grand and upright piano?", options: ["Size and soundboard angle", "Number of keys", "Sound quality only", "Price only"], answer: "Size and soundboard angle" },
            { question: "What is a Steinway piano known for?", options: ["Being cheapest", "High quality construction", "Electronic", "Portable"], answer: "High quality construction" },
            { question: "What is the function of the soft pedal on a piano?", options: ["Makes notes louder", "Shifts the piano mechanism", "Sustains indefinitely", "Adds reverb"], answer: "Shifts the piano mechanism" },
            { question: "What is a chord progression in classical music on piano?", options: ["Random notes", "Organized sequence of chords", "Single note repeated", "Rhythm only"], answer: "Organized sequence of chords" },
            { question: "What is a Alberti bass pattern?", options: ["Complex rhythm", "Simple broken chord pattern", "Bass clef only", "Treble clef only"], answer: "Simple broken chord pattern" },
            { question: "What notes make up a G major triad?", options: ["G-B-D", "G-A-D", "G-C-D", "G-B♭-D"], answer: "G-B-D" },
            { question: "What notes make up a D minor triad?", options: ["D-F-A", "D-F♯-A", "D-G-A", "D-E-A"], answer: "D-F-A" },
            { question: "What is voicing in piano chords?", options: ["Singing", "How notes are arranged", "Tempo marking", "Dynamics"], answer: "How notes are arranged" },
            { question: "What is a diminished triad?", options: ["Three notes with flattened fifth", "Three notes", "Two notes", "Five notes"], answer: "Three notes with flattened fifth" },
            { question: "What is an augmented triad?", options: ["Three notes with raised fifth", "Three notes", "Five notes", "Seven notes"], answer: "Three notes with raised fifth" },
            { question: "What is a major seventh chord built on C?", options: ["C-E-G-B", "C-E-G-B♭", "C-D-E-G", "C-E-F-B"], answer: "C-E-G-B" },
            { question: "What is a dominant seventh chord?", options: ["Fifth degree triad with minor seventh", "Fifth degree triad with major seventh", "Any seventh chord", "A diminished chord"], answer: "Fifth degree triad with minor seventh" },
            { question: "What is finger independence on piano?", options: ["Playing with one finger", "Each finger can move independently", "Fingers move together", "Using thumbs only"], answer: "Each finger can move independently" },
            { question: "What is proper posture for piano playing?", options: ["Slouched", "Straight back, relaxed shoulders, feet flat", "Leaning forward", "Head down"], answer: "Straight back, relaxed shoulders, feet flat" },
            { question: "What is a scale run on piano?", options: ["Playing scattered notes", "Playing scale notes in quick succession", "Playing chords", "Playing one note"], answer: "Playing scale notes in quick succession" },
            { question: "What is the purpose of piano technique?", options: ["Speed only", "Accuracy, speed, control, and expression", "Loudness", "Softness"], answer: "Accuracy, speed, control, and expression" },
            { question: "What is a passing tone in piano playing?", options: ["A chord note", "A non-chord tone connecting melody", "A resting note", "A loud note"], answer: "A non-chord tone connecting melody" },
            { question: "What is counterpoint on piano?", options: ["One melody", "Two or more independent melodies", "Chords", "Rhythm"], answer: "Two or more independent melodies" },
            { question: "What is a suspension on piano?", options: ["Stopping mid-phrase", "Note held from previous chord", "Quick notes", "Long notes"], answer: "Note held from previous chord" },
            { question: "What is a key change on piano?", options: ["Playing different keys", "Modulating to a different key", "Pressing keys differently", "Using different fingers"], answer: "Modulating to a different key" },
            { question: "What is a cadenza on piano?", options: ["A cadence", "An ornamental solo passage", "A chord progression", "A scale"], answer: "An ornamental solo passage" },
            { question: "What does 'legato' mean on piano?", options: ["Separated notes", "Connected smooth notes", "Loud notes", "Soft notes"], answer: "Connected smooth notes" },
            { question: "What does 'staccato' mean on piano?", options: ["Smooth", "Separated short notes", "Long notes", "Loud notes"], answer: "Separated short notes" },
            { question: "What is a trill on piano?", options: ["Quick note succession", "Alternating two notes rapidly", "Scale", "Arpeggio"], answer: "Alternating two notes rapidly" },
            { question: "What is a turn ornament?", options: ["Rotating wrist", "Notes going up-down-up or down-up-down", "Chord", "Scale"], answer: "Notes going up-down-up or down-up-down" },
            { question: "What notes make up an F major triad?", options: ["F-A-C", "F-A♭-C", "F-G-C", "F-B♭-C"], answer: "F-A-C" },
            { question: "What notes make up an E minor triad?", options: ["E-G-B", "E-G♯-B", "E-A-B", "E-F-B"], answer: "E-G-B" },
            { question: "What is the benefit of practicing scales on piano?", options: ["Wasting time", "Building finger strength and familiarity with keys", "Not useful", "Boring only"], answer: "Building finger strength and familiarity with keys" },
            { question: "What is a grace note on piano?", options: ["Note of grace", "Ornamental note played quickly before main note", "Main melody", "Chord tone"], answer: "Ornamental note played quickly before main note" },
            { question: "What is mordent on piano?", options: ["Holding a note", "Quick alternation with adjacent note", "Scale", "Arpeggio"], answer: "Quick alternation with adjacent note" }
        ],
        advanced: [
            { question: "What is a Schumann technique on piano?", options: ["Fast scales", "Finger independence through exercises", "Loud playing", "Soft playing"], answer: "Finger independence through exercises" },
            { question: "What is the Hanon method?", options: ["Music theory", "50+ finger exercises for technique", "Composition method", "Listening method"], answer: "50+ finger exercises for technique" },
            { question: "What is Czerny in piano study?", options: ["Composer", "Creator of progressive piano studies", "Instrument maker", "Performance style"], answer: "Creator of progressive piano studies" },
            { question: "What is the Liszt technique on piano?", options: ["Slow playing", "Virtuosic rapid passages and transcendental difficulty", "Chord-based", "Minimalist"], answer: "Virtuosic rapid passages and transcendental difficulty" },
            { question: "What is a chromatic scale on piano?", options: ["All white keys", "All black keys", "All semitones including black and white", "Every other key"], answer: "All semitones including black and white" },
            { question: "What is a whole tone scale?", options: ["All intervals are whole steps", "All intervals are semitones", "Diatonic scale", "Pentatonic scale"], answer: "All intervals are whole steps" },
            { question: "What is a pentatonic scale?", options: ["Five notes", "Seven notes", "Twelve notes", "Three notes"], answer: "Five notes" },
            { question: "What is partimento in piano?", options: ["Part time job", "Improvisation from figured bass", "Sheet music", "Chord chart"], answer: "Improvisation from figured bass" },
            { question: "What is a figured bass?", options: ["Musical notations for inversions", "Rhythm notation", "Lyrics", "Fingering guide"], answer: "Musical notations for inversions" },
            { question: "What is rubato in piano playing?", options: ["Strict tempo", "Flexible tempo with give and take", "No expression", "Mechanical playing"], answer: "Flexible tempo with give and take" },
            { question: "What is a cluster chord on piano?", options: ["Normal triad", "Many adjacent notes played together", "Separated notes", "Melodic notes"], answer: "Many adjacent notes played together" },
            { question: "What is tone production on piano?", options: ["Volume only", "Resonance and quality of sound", "Speed", "Technique"], answer: "Resonance and quality of sound" },
            { question: "What is pedal technique?", options: ["Not important", "Careful use of sustain, soft, and una corda pedals", "Using all pedals always", "Ignoring pedals"], answer: "Careful use of sustain, soft, and una corda pedals" },
            { question: "What is repertoire building?", options: ["Playing same piece", "Gradually learning diverse pieces", "Not learning", "Avoiding classics"], answer: "Gradually learning diverse pieces" },
            { question: "What is a cadential six-four chord?", options: ["Random chord", "I 6/4 before V-I cadence", "Seventh chord", "Diminished chord"], answer: "I 6/4 before V-I cadence" },
            { question: "What is voice leading in piano?", options: ["Singing", "Smooth progression between chords", "No rules", "Random notes"], answer: "Smooth progression between chords" },
            { question: "What is a Rachmaninoff technique?", options: ["Slow playing", "Large hand spans and dense chords", "Minimalist", "Pop style"], answer: "Large hand spans and dense chords" },
            { question: "What is sight-reading on piano?", options: ["Looking at audience", "Reading and playing unfamiliar music", "Memorization", "Improvisation"], answer: "Reading and playing unfamiliar music" },
            { question: "What is a nocturne?", options: ["Night music with lyrical melody and accompaniment", "Fast music", "Loud music", "Soft only"], answer: "Night music with lyrical melody and accompaniment" },
            { question: "What is a polonaise?", options: ["Slow waltz", "Stately Polish dance in 3/4 time", "Rapid rondo", "Ballad"], answer: "Stately Polish dance in 3/4 time" },
            { question: "What is a mazurka?", options: ["Fast run", "Polish folk dance in triple meter", "Blues", "Raga"], answer: "Polish folk dance in triple meter" },
            { question: "What is a prelude?", options: ["After the main piece", "Short introductory piece", "Long piece", "Finale"], answer: "Short introductory piece" },
            { question: "What is an etude?", options: ["Story", "Composition designed to improve technique", "Song", "Dance"], answer: "Composition designed to improve technique" },
            { question: "What is polytonality on piano?", options: ["One key", "Multiple keys simultaneously", "Modulation", "No key"], answer: "Multiple keys simultaneously" },
            { question: "What is atonality on piano?", options: ["No tone", "No tonal center", "Only one tone", "All tones equal"], answer: "No tonal center" },
            { question: "What is serialism on piano?", options: ["Serial numbers", "12-tone compositional method", "Serial music", "Not a method"], answer: "12-tone compositional method" },
            { question: "What is a glissando technique?", options: ["Smooth chords", "Sliding finger across keys", "Rapid notes", "Slow notes"], answer: "Sliding finger across keys" },
            { question: "What is a prepared piano?", options: ["Piano tuned well", "Objects placed on strings to change sound", "New piano", "Old piano"], answer: "Objects placed on strings to change sound" },
            { question: "What is extended technique on piano?", options: ["Long pieces", "Playing inside piano or unconventional methods", "Standard technique", "Practice"], answer: "Playing inside piano or unconventional methods" },
            { question: "What is interpretive performance?", options: ["Reading score", "Adding personal expression within score guidelines", "Ignoring composer", "Changing notes"], answer: "Adding personal expression within score guidelines" }
        ]
    },
    guitar: {
        beginner: [
            { question: "On a standard guitar, how many strings are there?", options: ["4", "5", "7", "6"], answer: "6" },
            { question: "Standard guitar tuning from lowest to highest starts with:", options: ["A", "D", "G", "E"], answer: "E" },
            { question: "What is the standard guitar tuning (low to high)?", options: ["E-A-D-G-B-e", "C-F-B♭-E♭-G-D", "A-D-G-C-E-A", "E-B-G-D-A-E"], answer: "E-A-D-G-B-e" },
            { question: "What is a fret on a guitar?", options: ["A string", "A metal ridge that changes note pitch", "A chord", "A strum"], answer: "A metal ridge that changes note pitch" },
            { question: "How many frets does a typical acoustic guitar have?", options: ["12", "20", "22", "24"], answer: "20" },
            { question: "What is a pick on a guitar?", options: ["A chord", "A tool to pluck strings", "A tuning device", "A capo"], answer: "A tool to pluck strings" },
            { question: "What is a capo?", options: ["A chord", "A device to shorten string length", "A tuning peg", "A pick"], answer: "A device to shorten string length" },
            { question: "What does 'fingerstyle' mean on guitar?", options: ["Using a pick", "Plucking strings with fingers", "Using a bow", "Strumming"], answer: "Plucking strings with fingers" },
            { question: "What is a power chord on guitar?", options: ["A full triad", "Root and fifth notes", "A seventh chord", "A sus chord"], answer: "Root and fifth notes" },
            { question: "What is an open chord on guitar?", options: ["A chord with all strings open", "A chord using open strings", "A chord without a root", "Any chord"], answer: "A chord using open strings" },
            { question: "What is a barre chord?", options: ["A chord played with fingers", "Using one finger across multiple strings", "An open chord", "A power chord"], answer: "Using one finger across multiple strings" },
            { question: "What notes make up a G major chord on guitar?", options: ["G-B-D", "G-A-D", "G-C-D", "G-B♭-D"], answer: "G-B-D" },
            { question: "What notes make up an E minor chord on guitar?", options: ["E-G-B", "E-G♯-B", "E-A-B", "E-F-B"], answer: "E-G-B" },
            { question: "What is a guitar strap?", options: ["A tuning device", "A belt around the body", "A string", "A pick"], answer: "A belt around the body" },
            { question: "What is the sound hole on an acoustic guitar?", options: ["A fret", "An opening where sound emerges", "A tuning peg", "A bridge"], answer: "An opening where sound emerges" },
            { question: "What is the bridge on a guitar?", options: ["A musical phrase", "A device where strings attach", "A chord", "A tuning method"], answer: "A device where strings attach" },
            { question: "What is the headstock on a guitar?", options: ["Where you rest your head", "Part with tuning pegs", "The body", "The bridge"], answer: "Part with tuning pegs" },
            { question: "What is strumming on a guitar?", options: ["Plucking individual strings", "Moving pick across strings", "Using a bow", "Tapping frets"], answer: "Moving pick across strings" },
            { question: "What is finger muting on guitar?", options: ["Using a damper", "Lightly touching strings to stop sound", "Not playing", "Soft playing"], answer: "Lightly touching strings to stop sound" },
            { question: "What is palm muting on guitar?", options: ["Using hand", "Resting palm on strings near bridge", "Stopping strings", "Deadening technique"], answer: "Resting palm on strings near bridge" },
            { question: "What is a vibrato on guitar?", options: ["Changing volume", "Varying pitch by bending string", "Fast playing", "Slow playing"], answer: "Varying pitch by bending string" },
            { question: "What is a hammer-on on guitar?", options: ["Hitting strings", "Fretting note without picking", "A tool", "A pick"], answer: "Fretting note without picking" },
            { question: "What is a pull-off on guitar?", options: ["Removing capo", "Releasing finger to play lower note", "Picking", "Strumming"], answer: "Releasing finger to play lower note" },
            { question: "What is a slide on guitar?", options: ["Not staying still", "Moving finger along string to another fret", "A chord", "A scale"], answer: "Moving finger along string to another fret" },
            { question: "What is a bend on guitar?", options: ["Bending the body", "Pushing string to raise pitch", "Lowering pitch", "A chord"], answer: "Pushing string to raise pitch" },
            { question: "What is a tremolo on guitar?", options: ["Changing key", "Varying amplitude quickly", "Changing tempo", "Vibrato"], answer: "Varying amplitude quickly" },
            { question: "What is a trill on guitar?", options: ["Quick notes", "Rapid alternation between two pitches", "Scale", "Arpeggio"], answer: "Rapid alternation between two pitches" },
            { question: "What is fingerpicking on guitar?", options: ["Picking one string", "Plucking strings with individual fingers", "Using a pick", "Strumming"], answer: "Plucking strings with individual fingers" },
            { question: "What is a scale on guitar?", options: ["Weighing", "Series of notes in ascending/descending order", "Chords", "Rhythm"], answer: "Series of notes in ascending/descending order" },
            { question: "What is alternate picking?", options: ["Picking same direction", "Alternating down and up pick strokes", "One direction", "Two picks"], answer: "Alternating down and up pick strokes" }
        ],
        intermediate: [
            { question: "What is a sus2 chord on guitar?", options: ["Suspended with 2nd", "A major seventh", "A power chord", "A diminished chord"], answer: "Suspended with 2nd" },
            { question: "What is a sus4 chord on guitar?", options: ["Suspended with 4th", "A major seventh", "A minor chord", "A seventh chord"], answer: "Suspended with 4th" },
            { question: "What is a relative minor on guitar?", options: ["A chord", "A key with same notes as major", "A scale", "An interval"], answer: "A key with same notes as major" },
            { question: "What is a pentatonic scale on guitar?", options: ["Seven notes", "Five-note scale", "Twelve notes", "Three notes"], answer: "Five-note scale" },
            { question: "What is a major pentatonic scale?", options: ["1-2-3-5-6 scale degrees", "1-3-5-6-8", "All black keys", "Blues scale"], answer: "1-2-3-5-6 scale degrees" },
            { question: "What is a minor pentatonic scale?", options: ["1-3-4-5-7", "1-3-5-7-8", "All black keys", "Chromatic scale"], answer: "1-3-4-5-7" },
            { question: "What is the blues scale on guitar?", options: ["Minor pentatonic", "Minor pentatonic with added flat 5", "Major scale", "Chromatic scale"], answer: "Minor pentatonic with added flat 5" },
            { question: "What is a chord progression on guitar?", options: ["Single chord", "Series of chords", "Melody", "Rhythm pattern"], answer: "Series of chords" },
            { question: "What is a I-IV-V progression?", options: ["Uncommon", "Classic progression", "Not playable", "Random chords"], answer: "Classic progression" },
            { question: "What is fingering on guitar?", options: ["Touching", "Using specific fingers for technique", "Counting", "Noting"], answer: "Using specific fingers for technique" },
            { question: "What is a drop D tuning on guitar?", options: ["Standard tuning", "Lowering 6th string to D", "Raising strings", "Tuning method"], answer: "Lowering 6th string to D" },
            { question: "What is an open G tuning on guitar?", options: ["Standard E-A-D-G-B-e", "Tuning strings for G chord", "Tuning method", "A capo"], answer: "Tuning strings for G chord" },
            { question: "What is chord substitution on guitar?", options: ["Not playing", "Replacing chord with similar sounding", "Random change", "No rule"], answer: "Replacing chord with similar sounding" },
            { question: "What is a chord inversion on guitar?", options: ["Flipping chord", "Playing chord notes in different order", "Strumming pattern", "Muting technique"], answer: "Playing chord notes in different order" },
            { question: "What is arpeggiation on guitar?", options: ["Playing chord as single unit", "Playing chord notes individually", "Strumming", "Picking all at once"], answer: "Playing chord notes individually" },
            { question: "What is a riff on guitar?", options: ["A chord", "Repeated melodic phrase", "Scale", "Tuning"], answer: "Repeated melodic phrase" },
            { question: "What is a lick on guitar?", options: ["Candy", "Short melodic phrase or solo", "Chord", "Technique"], answer: "Short melodic phrase or solo" },
            { question: "What is legato on guitar?", options: ["Separated notes", "Smooth connected notes", "Staccato", "Bouncy"], answer: "Smooth connected notes" },
            { question: "What is sweep picking on guitar?", options: ["Cleaning", "Picking across strings in one motion", "Strumming", "Tapping"], answer: "Picking across strings in one motion" },
            { question: "What is tapping on guitar?", options: ["Percussion", "Fretting by tapping fretboard", "Touching softly", "Light strumming"], answer: "Fretting by tapping fretboard" },
            { question: "What is a natural harmonic on guitar?", options: ["Artificial effect", "Playing open string touching node", "Tuning method", "A scale"], answer: "Playing open string touching node" },
            { question: "What is an artificial harmonic on guitar?", options: ["Natural sound", "Playing while touching specific fret position", "Pedal effect", "Recording"], answer: "Playing while touching specific fret position" },
            { question: "What is feedback on electric guitar?", options: ["Comments", "Amplified string vibration", "Echo", "Distortion"], answer: "Amplified string vibration" },
            { question: "What is a power chord on guitar?", options: ["Full triad", "Two-note root and fifth", "Seven chord", "Sus chord"], answer: "Two-note root and fifth" },
            { question: "What is string bending on guitar?", options: ["Breaking string", "Pushing string to raise pitch", "Lowering pitch", "Tuning"], answer: "Pushing string to raise pitch" },
            { question: "What is vibrato bar on guitar?", options: ["Smooth playing", "Whammy bar for pitch variation", "Tuning device", "Volume control"], answer: "Whammy bar for pitch variation" },
            { question: "What is delay on electric guitar?", options: ["Slow tempo", "Echo effect", "Reverb", "Distortion"], answer: "Echo effect" },
            { question: "What is reverb on electric guitar?", options: ["Going backward", "Echo and space effect", "Distortion", "Echo only"], answer: "Echo and space effect" },
            { question: "What is overdrive on guitar?", options: ["Too much", "Mild distortion", "Heavy distortion", "Clean sound"], answer: "Mild distortion" },
            { question: "What is distortion on electric guitar?", options: ["Unclear", "Heavy saturation and clipping", "Clean sound", "Mild effect"], answer: "Heavy saturation and clipping" }
        ],
        advanced: [
            { question: "What is modal interchange on guitar?", options: ["Key change", "Using chords from parallel modes", "Scale", "Tuning"], answer: "Using chords from parallel modes" },
            { question: "What is polyrhythm on guitar?", options: ["One rhythm", "Multiple simultaneous rhythms", "Complex rhythm", "No rhythm"], answer: "Multiple simultaneous rhythms" },
            { question: "What is rhythmic displacement on guitar?", options: ["No rhythm", "Shifting phrase across beats", "Syncopation", "Offbeats"], answer: "Shifting phrase across beats" },
            { question: "What is a tritone substitution on guitar?", options: ["Random substitution", "Replacing chord with tritone relation", "Scale change", "Tuning change"], answer: "Replacing chord with tritone relation" },
            { question: "What is voice leading on guitar?", options: ["Singing", "Smooth chord progressions", "Chords", "Melody"], answer: "Smooth chord progressions" },
            { question: "What is a Dorian mode on guitar?", options: ["Natural minor with raised 7", "Natural minor with raised 6", "Major with lowered 3 and 7", "Pentatonic scale"], answer: "Natural minor with raised 7" },
            { question: "What is a Phrygian mode on guitar?", options: ["Natural minor with raised 2", "Natural minor with lowered 2", "Natural minor with raised 6", "Major scale"], answer: "Natural minor with lowered 2" },
            { question: "What is a Lydian mode on guitar?", options: ["Major with lowered 4", "Major with raised 4", "Major scale", "Minor scale"], answer: "Major with raised 4" },
            { question: "What is a Mixolydian mode on guitar?", options: ["Major with raised 7", "Major with lowered 7", "Minor scale", "Blues scale"], answer: "Major with lowered 7" },
            { question: "What is a Locrian mode on guitar?", options: ["Natural minor with raised 2 and 5", "Natural minor with lowered 2 and 5", "Major scale", "Pentatonic"], answer: "Natural minor with lowered 2 and 5" },
            { question: "What is chromatic scale on guitar?", options: ["All white notes", "All semitones", "Diatonic", "Pentatonic"], answer: "All semitones" },
            { question: "What is a whole tone scale on guitar?", options: ["One tone", "All whole step intervals", "Pentatonic", "Blues scale"], answer: "All whole step intervals" },
            { question: "What is an augmented triad on guitar?", options: ["Three notes", "Triad with raised fifth", "Triad with lowered fifth", "Seven chord"], answer: "Triad with raised fifth" },
            { question: "What is a diminished seventh chord on guitar?", options: ["Minor seventh", "Diminished triad with lowered seventh", "Augmented seventh", "Major seventh"], answer: "Diminished triad with lowered seventh" },
            { question: "What is an extended technique on guitar?", options: ["Long playing", "Unconventional methods like inside playing", "Distortion", "Effects"], answer: "Unconventional methods like inside playing" },
            { question: "What is prepared guitar?", options: ["Tuned well", "Objects on strings to change sound", "Clean guitar", "New guitar"], answer: "Objects on strings to change sound" },
            { question: "What is a tremolo technique on guitar?", options: ["Bending", "Varying volume rapidly", "Changing pitch", "Distortion"], answer: "Varying volume rapidly" },
            { question: "What is a slide rule on guitar?", options: ["Measurement", "Playing multiple notes by sliding", "Tuning method", "Picking"], answer: "Playing multiple notes by sliding" },
            { question: "What is a harmonic minor scale on guitar?", options: ["Natural minor with raised 6", "Natural minor with raised 7", "Natural minor", "Major scale"], answer: "Natural minor with raised 7" },
            { question: "What is a melodic minor scale on guitar?", options: ["Natural minor with raised 6 and 7", "Natural minor", "Major scale", "Pentatonic"], answer: "Natural minor with raised 6 and 7" },
            { question: "What is a neapolitan chord on guitar?", options: ["Italian chord", "Flattened supertonic chord", "Dominant", "Random"], answer: "Flattened supertonic chord" },
            { question: "What is guitar soloing?", options: ["Playing alone", "Improvised melodic playing", "Playing chords", "Rhythmic playing"], answer: "Improvised melodic playing" },
            { question: "What is chicken picking on guitar?", options: ["Poultry style", "Hybrid picking technique", "Fingerstyle", "Strumming"], answer: "Hybrid picking technique" },
            { question: "What is slap technique on guitar?", options: ["Hitting", "Percussive striking of strings", "Normal picking", "Strumming"], answer: "Percussive striking of strings" },
            { question: "What is percussive muting on guitar?", options: ["Silent", "Muting for rhythmic effect", "No sound", "Stopping"], answer: "Muting for rhythmic effect" },
            { question: "What is a whammy bar technique?", options: ["Hitting hard", "Vibrato bar control for pitch", "Feedback", "Distortion"], answer: "Vibrato bar control for pitch" },
            { question: "What is phase shifting on guitar?", options: ["Changing phase", "Chorus-like effect", "Distortion", "Reverb"], answer: "Chorus-like effect" },
            { question: "What is compression on guitar?", options: ["Squeezing strings", "Controlling dynamic range", "Distortion", "Reverb"], answer: "Controlling dynamic range" },
            { question: "What is frequency in guitar tone?", options: ["Pitch range", "How often string vibrates", "Resonance", "Amplification"], answer: "How often string vibrates" },
            { question: "What is impedance on guitar?", options: ["Blocking", "Electrical resistance", "Volume", "Tuning"] , answer: "Electrical resistance" }
        ]
    },
    drums: {
        beginner: [
            { question: "How many main pieces does a drum kit have?", options: ["3", "5", "7", "10"], answer: "5" },
            { question: "What are the main drums in a kit?", options: ["Just snare", "Bass, tom, snare", "Bass drum, toms, snare drum, hi-hat, cymbals", "Only cymbals"], answer: "Bass drum, toms, snare drum, hi-hat, cymbals" },
            { question: "What is the bass drum?", options: ["A kick drum", "The drum played with foot pedal", "Lowest pitched drum", "All of the above"], answer: "All of the above" },
            { question: "What is the snare drum?", options: ["Caught in a trap", "Upper-mid pitch drum with snares on bottom", "A cymbal", "A gong"], answer: "Upper-mid pitch drum with snares on bottom" },
            { question: "What is the snare on a snare drum?", options: ["A rope", "Metal wires across bottom", "A brush", "A stick"], answer: "Metal wires across bottom" },
            { question: "What are toms on a drum kit?", options: ["Cats", "Mid-range drums", "Cymbals", "Percussion"], answer: "Mid-range drums" },
            { question: "How many toms does a typical drum kit have?", options: ["1", "2", "3", "4"], answer: "2" },
            { question: "What are the tom sizes typically?", options: ["All same", "Small, medium, large", "High tom and floor tom", "Random sizes"], answer: "High tom and floor tom" },
            { question: "What is a floor tom?", options: ["A tom on the floor", "Large tom with legs", "A kick drum", "A cymbal"], answer: "Large tom with legs" },
            { question: "What is a hi-hat?", options: ["A hat", "Pair of cymbals on stand", "A type of drum", "A brush"], answer: "Pair of cymbals on stand" },
            { question: "How do you play the hi-hat?", options: ["With hands", "With foot pedal", "Both hands and foot", "With brushes only"], answer: "Both hands and foot" },
            { question: "What does closing the hi-hat do?", options: ["Opens it", "Creates sharp sound", "Makes it louder", "Lowers pitch"], answer: "Creates sharp sound" },
            { question: "What is a kick drum?", options: ["A bass drum", "Played with foot pedal", "Lowest note drum", "All of the above"], answer: "All of the above" },
            { question: "What is a drum head?", options: ["Your head", "Skin covering drum", "A cymbals", "A stick"], answer: "Skin covering drum" },
            { question: "What is a drumstick?", options: ["A stick for the snare", "Tool to play drums", "A wooden stick", "All of the above"], answer: "All of the above" },
            { question: "What are brush", options: ["Plant tool", "Retractable wires for softer sound", "Cleaning tool", "Cymbal brush"], answer: "Retractable wires for softer sound" },
            { question: "What is a drum key?", options: ["Music key", "Tool to tighten lugs", "Tuning device", "Key signature"], answer: "Tool to tighten lugs" },
            { question: "What is tuning on drums?", options: ["Listening", "Tightening heads for pitch", "Replacing heads", "Cleaning"], answer: "Tightening heads for pitch" },
            { question: "What is tempo in drumming?", options: ["Sound", "Speed of beat", "Rhythm", "Beat pattern"], answer: "Speed of beat" },
            { question: "What is a beat on drums?", options: ["Music", "Repeated rhythm pattern", "Sound", "Note"], answer: "Repeated rhythm pattern" },
            { question: "What is a fill on drums?", options: ["To fill space", "Improvised drum pattern between sections", "Whole song", "Ending only"], answer: "Improvised drum pattern between sections" },
            { question: "What is a crash cymbal?", options: ["Broken", "Large cymbal for dramatic sound", "Hi-hat", "Small cymbal"], answer: "Large cymbal for dramatic sound" },
            { question: "What is a ride cymbal?", options: ["To ride on", "Medium cymbal with clear pitch", "Crash cymbal", "Hi-hat"], answer: "Medium cymbal with clear pitch" },
            { question: "What is a double kick?", options: ["Two kicks", "Two bass drums or double pedal", "Double kick technique", "All of the above"], answer: "All of the above" },
            { question: "What is a drum paradiddle?", options: ["A sound", "Drum rudiment pattern", "Rhythm", "Technique"], answer: "Drum rudiment pattern" },
            { question: "What is a drum roll?", options: ["Rolling drum", "Rapid repeated strokes", "Whole song", "Long sound"], answer: "Rapid repeated strokes" },
            { question: "What is ghost notes on drums?", options: ["Haunted", "Quiet unaccented notes", "Main beat", "Loud notes"], answer: "Quiet unaccented notes" },
            { question: "What is dynamic control on drums?", options: ["Changing nothing", "Varying volume and intensity", "Playing loud", "Playing soft"], answer: "Varying volume and intensity" },
            { question: "What is pocket in drumming?", options: ["Place to store", "Tight rhythmic feel", "No rhythm", "Random timing"], answer: "Tight rhythmic feel" },
            { question: "What is swing in drumming?", options: ["Swinging", "Triplet-based rhythm feel", "Rock feel", "Straight rhythm"], answer: "Triplet-based rhythm feel" }
        ],
        intermediate: [
            { question: "What is a drum rudiment?", options: ["Rude behavior", "Basic sticking pattern", "Technique", "Exercise"], answer: "Basic sticking pattern" },
            { question: "How many essential drum rudiments are there?", options: ["5", "10", "40", "26"], answer: "40" },
            { question: "What is a single stroke roll?", options: ["Random strokes", "Alternating hands continuously", "Both hands same stroke", "No pattern"], answer: "Alternating hands continuously" },
            { question: "What is a double stroke roll?", options: ["Two rolls", "Two strokes per hand", "Random strokes", "Complex pattern"], answer: "Two strokes per hand" },
            { question: "What is a flam on drums?", options: ["Flat sound", "Quick grace note before main note", "Rudiment", "Technique"], answer: "Quick grace note before main note" },
            { question: "What is a drag on drums?", options: ["Pulling", "Quick notes before main beat", "Rudiment variation", "Technique"], answer: "Quick notes before main beat" },
            { question: "What is a paradiddle on drums?", options: ["Strange sound", "Sticking pattern with single-double", "Complex rudiment", "Technique"], answer: "Sticking pattern with single-double" },
            { question: "What is a ratamacue on drums?", options: ["Rat sound", "Five-stroke rudiment", "Sticking pattern", "Technique"], answer: "Five-stroke rudiment" },
            { question: "What is blast beats on drums?", options: ["Explosion", "Rapid kick and snare", "Metal technique", "All of the above"], answer: "All of the above" },
            { question: "What is polyrhythm on drums?", options: ["One rhythm", "Multiple rhythms simultaneously", "Complex rhythm", "No rhythm"], answer: "Multiple rhythms simultaneously" },
            { question: "What is a kick pattern on drums?", options: ["Foot pattern", "Bass drum rhythmic pattern", "Kick sound", "Pedal"], answer: "Bass drum rhythmic pattern" },
            { question: "What is a snare pattern on drums?", options: ["Snare sound", "Snare drum rhythm", "Drum head", "Wires"], answer: "Snare drum rhythm" },
            { question: "What is ostinato on drums?", options: ["Italian food", "Repeated rhythm pattern", "Changing pattern", "Random beats"], answer: "Repeated rhythm pattern" },
            { question: "What is syncopation on drums?", options: ["Off-beat emphasis", "Emphasizing weak beats", "All notes equal", "No accent"], answer: "Emphasizing weak beats" },
            { question: "What is groove on drums?", options: ["Hole", "Rhythmic feel and swing", "Tempo", "Style"], answer: "Rhythmic feel and swing" },
            { question: "What is a jazz drumming style?", options: ["Always fast", "Swing feel, ride cymbal, hi-hat variations", "Rock style", "Metal style"], answer: "Swing feel, ride cymbal, hi-hat variations" },
            { question: "What is a rock drumming style?", options: ["Stone sound", "Straight beats, kick-snare emphasis", "Jazz feel", "Metal feel"], answer: "Straight beats, kick-snare emphasis" },
            { question: "What is a metal drumming style?", options: ["Metal instruments", "Fast kick, aggressive snare", "Soft playing", "Swing feel"], answer: "Fast kick, aggressive snare" },
            { question: "What is a funk drumming style?", options: ["Bad smell", "Syncopated groove", "Straight beats", "Jazz feel"], answer: "Syncopated groove" },
            { question: "What is rebound control on drums?", options: ["No bounce", "Controlling stick bounce", "Stick technique", "Hand control"], answer: "Controlling stick bounce" },
            { question: "What is hand technique on drums?", options: ["Using hands", "Grip, wrist motion, finger control", "Drumstick", "Sound"], answer: "Grip, wrist motion, finger control" },
            { question: "What is foot technique on drums?", options: ["Using feet", "Pedal control and hi-hat operation", "Kick sound", "Pedal"], answer: "Pedal control and hi-hat operation" },
            { question: "What is dynamic range on drums?", options: ["Volume range", "From soft to loud", "Contrast", "All of the above"], answer: "All of the above" },
            { question: "What is tom rolls on drums?", options: ["Tom sound", "Rapid strokes across toms", "Technique", "Pattern"], answer: "Rapid strokes across toms" },
            { question: "What is a cymbal crash?", options: ["Broken", "Strike creating dramatic sound", "Cymbal sound", "Impact"], answer: "Strike creating dramatic sound" },
            { question: "What is a cymbal chick?", options: ["Baby", "Sharp hi-hat closing sound", "Hi-hat", "Closed sound"], answer: "Sharp hi-hat closing sound" },
            { question: "What is a splash cymbal?", options: ["Water", "Small crash cymbal", "Quick sound", "Cymbal type"], answer: "Small crash cymbal" },
            { question: "What is tuning toms on drums?", options: ["Music key", "Adjusting head tension for pitch", "Drum pitch", "Head tension"], answer: "Adjusting head tension for pitch" },
            { question: "What is mic placement for drums?", options: ["Microphone position", "Strategic placement for recording", "Sound capture", "Recording technique"], answer: "Strategic placement for recording" },
            { question: "What is click track in drumming?", options: ["Hearing click", "Metronome reference", "Tempo reference", "Practice tool"], answer: "Metronome reference" }
        ],
        advanced: [
            { question: "What is moller technique on drums?", options: ["Inventor", "Wrist motion technique", "Hand technique", "Stick control"], answer: "Wrist motion technique" },
            { question: "What is matched grip on drums?", options: ["Same grip both hands", "Different hand grips", "Holding grip", "Stick grip"], answer: "Same grip both hands" },
            { question: "What is traditional grip on drums?", options: ["Old way", "Left hand holds stick differently", "Right hand different", "Ancient technique"], answer: "Left hand holds stick differently" },
            { question: "What is buzz stroke on drums?", options: ["Sound", "Roll using rebound", "Rudiment", "Technique"], answer: "Roll using rebound" },
            { question: "What is a press roll on drums?", options: ["Not pressing", "Pressing stick for sound", "Roll type", "Technique"], answer: "Pressing stick for sound" },
            { question: "What is playing behind the beat on drums?", options: ["Back hit", "Playing slightly after beat", "Lag timing", "Feel"], answer: "Playing slightly after beat" },
            { question: "What is playing ahead of the beat on drums?", options: ["Front hit", "Playing before beat", "Early timing", "Feel"], answer: "Playing before beat" },
            { question: "What is polymetric on drums?", options: ["One meter", "Multiple meters simultaneously", "Complex rhythm", "No meter"], answer: "Multiple meters simultaneously" },
            { question: "What is odd time on drums?", options: ["Wrong time", "Non-4/4 time signatures", "Unusual meter", "7/8, 5/4"], answer: "Non-4/4 time signatures" },
            { question: "What is swing eighths on drums?", options: ["Swinging", "Triplet feel eighth notes", "Straight eighths", "Feel type"], answer: "Triplet feel eighth notes" },
            { question: "What is shuffle rhythm on drums?", options: ["Randomness", "Triplet-based rhythm", "Feel type", "Technique"], answer: "Triplet-based rhythm" },
            { question: "What is cross-stick technique on drums?", options: ["Crossing sticks", "Hitting rim with stick", "Snare technique", "Sound variation"], answer: "Hitting rim with stick" },
            { question: "What is rim click on drums?", options: ["Resting", "Tapping rim for sharp sound", "Snare sound", "Stick technique"], answer: "Tapping rim for sharp sound" },
            { question: "What is open snare on drums?", options: ["Exposed", "Snare wires vibrating freely", "Sound", "Resonance"], answer: "Snare wires vibrating freely" },
            { question: "What is closed snare on drums?", options: ["Shut", "Dampening snare wires", "Sound", "Technique"], answer: "Dampening snare wires" },
            { question: "What is chop technique on drums?", options: ["Cutting", "Muting technique", "Hand control", "Dynamics"], answer: "Muting technique" },
            { question: "What is slave pedal in double kick?", options: ["Master", "Second kick pedal", "Foot control", "Kick technique"], answer: "Second kick pedal" },
            { question: "What is heel up vs heel down?", options: ["Foot position", "Different kick techniques", "Pedal control", "Foot technique"], answer: "Different kick techniques" },
            { question: "What is tension tuning on drums?", options: ["Stress", "Adjusting lugs evenly", "Pitch tuning", "Tuning method"], answer: "Adjusting lugs evenly" },
            { question: "What is batter head on drums?", options: ["Hitter head", "Top striking head", "Drum head", "Resonant"], answer: "Top striking head" },
            { question: "What is resonant head on drums?", options: ["Sounding head", "Bottom vibrating head", "Drum head", "Echo"], answer: "Bottom vibrating head" },
            { question: "What is bearing edge on drums?", options: ["Edge of bearing", "Shaping the drum shell edge", "Sound quality", "Tuning"], answer: "Shaping the drum shell edge" },
            { question: "What is a moeller whip on drums?", options: ["Whipping", "Motion creating power", "Technique variation", "Hand motion"], answer: "Motion creating power" },
            { question: "What is finger technique on drums?", options: ["Using fingers", "Finger independence", "Control", "Technique"], answer: "Finger independence" },
            { question: "What is bouncing in drumming?", options: ["Jumping", "Stick rebound control", "Stick technique", "Sound"], answer: "Stick rebound control" },
            { question: "What is articulation on drums?", options: ["Speech", "Clear note definition", "Sound clarity", "Attack"], answer: "Clear note definition" },
            { question: "What is ghost stroke on drums?", options: ["Spirit", "Quiet unaccented note", "Rhythm", "Feel"], answer: "Quiet unaccented note" },
            { question: "What is diddle on drums?", options: ["Nonsense", "Double sticking note", "Rudiment", "Pattern"], answer: "Double sticking note" },
            { question: "What is dynamics in drumming?", options: ["Motion", "Varying volume and intensity", "Softness and loudness", "Contrast"], answer: "Varying volume and intensity" },
            { question: "What is swing interpretation on drums?", options: ["Swinging on vine", "Adding swing feel to rhythm", "Style", "Feel"], answer: "Adding swing feel to rhythm" }
        ]
    },
    bass: {
        beginner: [
            { question: "How many strings does a standard bass have?", options: ["2", "3", "4", "5"], answer: "4" },
            { question: "What is the standard bass tuning (low to high)?", options: ["E-A-D-G", "E-A-D-G-B-E", "A-D-G-C", "E-B-F♯-C♯"], answer: "E-A-D-G" },
            { question: "What is the lowest note on a 4-string bass?", options: ["E1", "E2", "E0", "E3"], answer: "E1" },
            { question: "What type of bass uses a pick?", options: ["Upright bass", "Electric bass with pick", "Acoustic bass", "Double bass"], answer: "Electric bass with pick" },
            { question: "What is finger style bass playing?", options: ["Using a pick", "Plucking with fingers", "Using a bow", "Tapping"], answer: "Plucking with fingers" },
            { question: "Which bass technique uses index and middle fingers?", options: ["Slap and pop", "Alternate picking", "Two-finger plucking", "All of above"], answer: "Two-finger plucking" },
            { question: "What is slap bass?", options: ["Hitting softly", "Percussive thumb strike", "Technique", "Style"], answer: "Percussive thumb strike" },
            { question: "What is pop on bass?", options: ["A sound", "Snapping strings with fingers", "Technique", "Percussion"], answer: "Snapping strings with fingers" },
            { question: "What is the role of bass in a band?", options: ["Play melody", "Connect rhythm and harmony", "Lead instrument", "Background only"], answer: "Connect rhythm and harmony" },
            { question: "What is a bass line?", options: ["A line on staff", "Melodic rhythm pattern played by bass", "Guitar line", "Percussion"], answer: "Melodic rhythm pattern played by bass" },
            { question: "What is a root note on bass?", options: ["Dirt", "The fundamental note of a chord", "The lowest note", "All of above"], answer: "The fundamental note of a chord" },
            { question: "What is walking bass?", options: ["Moving slowly", "Rhythmic stepping pattern", "Jazz technique", "Chord tones"], answer: "Rhythmic stepping pattern" },
            { question: "What is a bass riff?", options: ["Torn", "Repeated bass phrase", "Melody", "Scale"], answer: "Repeated bass phrase" },
            { question: "What does dynamics on bass mean?", options: ["Motion", "Varying loudness", "Soft to loud", "All of above"], answer: "Varying loudness" },
            { question: "What is groove on bass?", options: ["Channel", "Tight rhythmic feel", "Tempo", "Pocket"], answer: "Tight rhythmic feel" },
            { question: "What is a bass clef?", options: ["A key", "Notation for low notes", "Music clef", "Bass notation"], answer: "Notation for low notes" },
            { question: "What is the range of a 4-string bass?", options: ["2 octaves", "3 octaves", "4 octaves", "5 octaves"], answer: "3 octaves" },
            { question: "What is a jazz bass?", options: ["Jazz style", "Short-scale bass", "Style of bass", "Music genre"], answer: "Short-scale bass" },
            { question: "What is a precision bass?", options: ["Accurate playing", "Fender design", "Bass type", "Solid single-coil"], answer: "Fender design" },
            { question: "What is a jazz bass pickup?", options: ["Musical instrument", "Dual split-coil pickup", "Sound", "Tone"], answer: "Dual split-coil pickup" },
            { question: "What is a bridge on bass?", options: ["Crossing structure", "Component where strings attach", "Hardware", "Tuning device"], answer: "Component where strings attach" },
            { question: "What is a pickup on electric bass?", options: ["Truck", "Transducer converting vibrations to signal", "Component", "Electronic"], answer: "Transducer converting vibrations to signal" },
            { question: "What is fretboard on bass?", options: ["Board games", "Where frets are", "Component", "Surface"], answer: "Where frets are" },
            { question: "What is thumb position on bass?", options: ["Finger position", "Position playing higher notes", "Technique", "Advanced playing"], answer: "Position playing higher notes" },
            { question: "What is octave on bass?", options: ["Eight notes", "Interval spanning 12 semitones", "Pitch doubling", "Range"], answer: "Interval spanning 12 semitones" },
            { question: "What is muting on bass?", options: ["Silent", "Dampening strings", "Technique", "No sound"], answer: "Dampening strings" },
            { question: "What is dead note on bass?", options: ["Deceased", "Muted percussive note", "Technique", "Rhythm"], answer: "Muted percussive note" },
            { question: "What is a harmonics on bass?", options: ["Harmony", "Flageolet tones", "Overtones", "Technique"], answer: "Flageolet tones" },
            { question: "What is natural harmonic on bass?", options: ["Normal sound", "Touching node points", "Technique", "Overtone"], answer: "Touching node points" },
            { question: "What is artificial harmonic on bass?", options: ["Not real", "Fretted harmonic", "Technique", "Overtone"], answer: "Fretted harmonic" }
        ],
        intermediate: [
            { question: "What is a 5-string bass tuning?", options: ["E-A-D-G-B", "B-E-A-D-G", "E-A-D-G-C", "A-D-G-C-F"], answer: "B-E-A-D-G" },
            { question: "What is a 6-string bass tuning?", options: ["E-A-D-G-B-E", "B-E-A-D-G-C", "E-A-D-G-C-F", "F-B♭-E♭-A♭-D♭-G♭"], answer: "B-E-A-D-G-C" },
            { question: "What is chord tones on bass?", options: ["Sound", "Notes that make up chords", "Melody", "Scales"], answer: "Notes that make up chords" },
            { question: "What is passing tone on bass?", options: ["Moving past", "Non-chord tone between harmonies", "Chord tone", "Scale tone"], answer: "Non-chord tone between harmonies" },
            { question: "What is anticipation on bass?", options: ["Expecting", "Playing next harmony early", "Syncopation", "Technique"], answer: "Playing next harmony early" },
            { question: "What is a suspension on bass?", options: ["Hanging", "Delaying chord resolution", "Chord", "Harmony"], answer: "Delaying chord resolution" },
            { question: "What is a bass fill?", options: ["Complete", "Improvised bass pattern", "Transition", "Solo"], answer: "Improvised bass pattern" },
            { question: "What is a bass solo?", options: ["Single", "Bass-only section", "Feature", "Improvisation"], answer: "Bass-only section" },
            { question: "What is rhythm feel on bass?", options: ["Emotion", "Groove and pocket", "Tempo", "Style"], answer: "Groove and pocket" },
            { question: "What is a funk bass line?", options: ["Bad", "Syncopated bass groove", "Style", "Feel"], answer: "Syncopated bass groove" },
            { question: "What is a reggae bass line?", options: ["Music genre", "Offbeat syncopated pattern", "Feel", "Style"], answer: "Offbeat syncopated pattern" },
            { question: "What is a latin bass clave?", options: ["Key", "Rhythmic pattern foundation", "Feel", "Rhythm"], answer: "Rhythmic pattern foundation" },
            { question: "What is polyrhythm on bass?", options: ["Many rhythms", "Multiple rhythms simultaneously", "Complex", "Technique"], answer: "Multiple rhythms simultaneously" },
            { question: "What is doubling in bass?", options: ["Two of same", "Playing same rhythm as another instrument", "Technique", "Arrangement"], answer: "Playing same rhythm as another instrument" },
            { question: "What is countermelody on bass?", options: ["Against melody", "Secondary melody", "Harmony", "Line"], answer: "Secondary melody" },
            { question: "What is voice leading on bass?", options: ["Singing", "Smooth chord progression", "Harmony", "Technique"], answer: "Smooth chord progression" },
            { question: "What is interval on bass?", options: ["Break", "Distance between notes", "Pitch", "Range"], answer: "Distance between notes" },
            { question: "What is a mode on bass?", options: ["Fashion", "Scale type from major/minor", "Scale", "Technique"], answer: "Scale type from major/minor" },
            { question: "What is a pentatonic scale on bass?", options: ["Five", "Five-note scale", "Scale", "Pattern"], answer: "Five-note scale" },
            { question: "What is a blues scale on bass?", options: ["Music style", "Minor pentatonic plus flat 5", "Scale", "Feel"], answer: "Minor pentatonic plus flat 5" },
            { question: "What is tone production on bass?", options: ["Sound quality", "How to create desired tone", "Technique", "Resonance"], answer: "How to create desired tone" },
            { question: "What is sustain on bass?", options: ["Continue", "Length of note duration", "Resonance", "Technique"], answer: "Length of note duration" },
            { question: "What is attack on bass?", options: ["Assault", "How note begins", "Technique", "Sound"], answer: "How note begins" },
            { question: "What is release on bass?", options: ["Letting go", "How note ends", "Technique", "Sound"], answer: "How note ends" },
            { question: "What is compression on bass?", options: ["Squeezing", "Dynamic range control", "Effect", "EQ"], answer: "Dynamic range control" },
            { question: "What is EQ on bass?", options: ["Equity", "Frequency equalization", "Tone shaping", "Effect"], answer: "Frequency equalization" },
            { question: "What is overdrive on bass?", options: ["Too much", "Mild distortion effect", "Effect", "Tone"], answer: "Mild distortion effect" },
            { question: "What is fuzz on bass?", options: ["Hair", "Heavy distortion", "Effect", "Tone"], answer: "Heavy distortion" },
            { question: "What is flanging on bass?", options: ["Sides", "Phasing effect", "Effect", "Sound"], answer: "Phasing effect" },
            { question: "What is chorus on bass?", options: ["Singing group", "Modulation effect", "Effect", "Sound"], answer: "Modulation effect" }
        ],
        advanced: [
            { question: "What is solfegio on bass?", options: ["Italian", "Note naming system", "Scale", "Technique"], answer: "Note naming system" },
            { question: "What is a diminished scale on bass?", options: ["Shorter", "Alternating whole-half steps", "Scale", "Pattern"], answer: "Alternating whole-half steps" },
            { question: "What is a whole tone scale on bass?", options: ["One tone", "All whole step intervals", "Scale", "Chromatic"], answer: "All whole step intervals" },
            { question: "What is modal interchange on bass?", options: ["Exchanging modes", "Using chords from parallel modes", "Technique", "Harmony"], answer: "Using chords from parallel modes" },
            { question: "What is tritone substitution on bass?", options: ["Three tone", "Replacing chord with tritone relation", "Substitution", "Technique"], answer: "Replacing chord with tritone relation" },
            { question: "What is a neapolitan chord on bass?", options: ["Italian", "Flattened supertonic harmony", "Chord", "Technique"], answer: "Flattened supertonic harmony" },
            { question: "What is augmented sixth on bass?", options: ["Bigger", "Secondary dominant preparation", "Chord", "Technique"], answer: "Secondary dominant preparation" },
            { question: "What is reharmonization on bass?", options: ["New harmony", "Creating alternative harmonies", "Technique", "Arrangement"], answer: "Creating alternative harmonies" },
            { question: "What is a pedal point on bass?", options: ["Pedal", "Held note while harmony changes", "Technique", "Harmony"], answer: "Held note while harmony changes" },
            { question: "What is basso continuo?", options: ["Bottom line", "Continuous bass accompaniment", "Baroque technique", "Foundation"], answer: "Continuous bass accompaniment" },
            { question: "What is figured bass?", options: ["Number bass", "Numeric notation for inversions", "Notation", "Baroque"], answer: "Numeric notation for inversions" },
            { question: "What is double bass technique?", options: ["Two bass", "Upright bass playing method", "Technique", "Instrument"], answer: "Upright bass playing method" },
            { question: "What is arco on upright bass?", options: ["Arc", "Playing with bow", "Technique", "Method"], answer: "Playing with bow" },
            { question: "What is pizzicato on upright bass?", options: ["Pizza", "Plucking strings", "Technique", "Method"], answer: "Plucking strings" },
            { question: "What is col legno on bass?", options: ["With wood", "Using bow wood", "Technique", "Extended"], answer: "Using bow wood" },
            { question: "What is harmonics on upright bass?", options: ["Harmony", "Overtone tones", "Technique", "Sound"], answer: "Overtone tones" },
            { question: "What is vibrato on upright bass?", options: ["Shaking", "Finger vibration on pitch", "Technique", "Expression"], answer: "Finger vibration on pitch" },
            { question: "What is glissando on bass?", options: ["Sliding", "Smooth pitch slide", "Technique", "Expression"], answer: "Smooth pitch slide" },
            { question: "What is microtonality on bass?", options: ["Small tones", "Playing between semitones", "Technique", "Advanced"], answer: "Playing between semitones" },
            { question: "What is extended range bass?", options: ["Wide", "5-string or more", "Bass type", "Range"], answer: "5-string or more" },
            { question: "What is symmetrical scale on bass?", options: ["Equal", "Even interval patterns", "Scale", "Pattern"], answer: "Even interval patterns" },
            { question: "What is applied dominant on bass?", options: ["Use", "Secondary dominant", "Harmony", "Technique"], answer: "Secondary dominant" },
            { question: "What is anticipatory note on bass?", options: ["Early", "Ahead-of-beat note", "Technique", "Rhythm"], answer: "Ahead-of-beat note" },
            { question: "What is implied harmony on bass?", options: ["Suggested", "Harmony suggested by bass line", "Technique", "Arrangement"], answer: "Harmony suggested by bass line" },
            { question: "What is rhythmic displacement on bass?", options: ["Moving rhythm", "Shifting phrase across beat", "Technique", "Rhythm"], answer: "Shifting phrase across beat" },
            { question: "What is metric modulation on bass?", options: ["Metric change", "Changing perceived meter", "Technique", "Time"], answer: "Changing perceived meter" },
            { question: "What is cross-rhythm on bass?", options: ["Crossing", "Multiple rhythms over each other", "Technique", "Polyrhythm"], answer: "Multiple rhythms over each other" },
            { question: "What is syncopation on bass?", options: ["Offsetting", "Emphasizing weak beats", "Technique", "Rhythm"], answer: "Emphasizing weak beats" },
            { question: "What is ostinato on bass?", options: ["Italian", "Repeated bass pattern", "Technique", "Groove"], answer: "Repeated bass pattern" },
            { question: "What is compositional bass?", options: ["Writing", "Bass line as composition", "Technique", "Arrangement"], answer: "Bass line as composition" }
        ]
    }
};

module.exports = questionBank;
